#pragma once
//#define HOMEKIT_DEBUG
#if defined(ARDUINO) && defined(ESP8266)
#define ARDUINO8266_SERVER

#define ARDUINO8266_SERVER_CPP

//#define HOMEKIT_DEBUG
#define HOMEKIT_SHORT_APPLE_UUIDS
#define HOMEKIT_OVERCLOCK_PAIR_SETUP
#endif 